### ISSUE TITLE
farmOS v3 support

### ISSUE THREAD

**Issue by paul121** [symbioquine/farmOS_wfs#1]
This module needs a few updates to declare support for farmOS v3 and Drupal 10. Likely just changing the `core_version_requirement` in `farmos_wfs.info.yml`. The tests could be updated to use the 3.x farmOS image as well.

I'm not as familiar with the code here but probably worth running `phpstan analyze` to see if there have been any breaking changes to things

**Comment by symbioquine** [comment]
Thanks @paul121 I might not get to this right away, but might be able to pull it up in my queue if it's blocking anybody... LMK if so.

**Comment by paul121** [comment]
No rush, not blocking me! Just going through updating/flagging modules that need it

**Comment by symbioquine** [comment]
farmOS_wfs has been updated to work with farmOS version 3.1.1 - https://www.drupal.org/project/farmos_wfs/releases/2.0.1
